name: Pull Request CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Run tests from gtest
      run: |
          cmake -B build -S .
          cmake --build build
          cd build && ctest --output-on-failure
